/*
* ============================================================================
*  Name     : CDummyProjApp from DummyProjApp.cpp
*  Part of  : DummyProj
*  Created  : 13/04/2005 by Mike Howson
*  Implementation notes:
*
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: Penrillian
* ============================================================================
*/

// INCLUDE FILES
#include    "DummyProjApp.h"
#include    "DummyProjDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CDummyProjApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CDummyProjApp::AppDllUid() const
    {
    return KUidDummyProj;
    }

   
// ---------------------------------------------------------
// CDummyProjApp::CreateDocumentL()
// Creates CDummyProjDocument object
// ---------------------------------------------------------
//
CApaDocument* CDummyProjApp::CreateDocumentL()
    {
    return CDummyProjDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CDummyProjApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CDummyProjApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

